### ISSUE TITLE
It always fails because added colon-mark in the end of the URL

### ISSUE THREAD

**Issue by hlovdahl** [zenhack/simp_le#110]
Hi,
Trying to register a new certificate always fails for me and when I looked at the Failing authorizaions url by opening it the browser, the URL that it tries to look at has a ":" appended to the end. No such file is ever generated on my server.
---
"Invalid response from http://myserver.com/.well-known/acme-challenge/FUAttLMn9mRY3kM9J6N34RsTljH2Yy3rlX4wgkn_QQ8: \"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p\""

**Comment by zenhack** [comment]
Can you provide some additional information? The below would be useful:

* Full output from the simp_le command
* How you are invoking simp_le (what arguments, etc)
* What version of simp_le you're using
* What your webserver setup is

**Comment by zenhack** [comment]
I'm going to close this, having not heard back for two weeks. If you're still having the problem, feel free to re-open and provide more info.
