### ISSUE TITLE
Any chance of storing account information?

### ISSUE THREAD

**Issue by x-yuri** [zenhack/simp_le#128]
Particularly, account email. Imagine yourself in a situation where you have obtained certificates, but don't know which account (email) was used to obtain them.

**Comment by buchdag** [comment]
This is already the case since the switch to ACME v2 ([version 0.15.0](https://github.com/zenhack/simp_le#0150)).

**Comment by zenhack** [comment]
Indeed, the newly generated `account_reg.json` includes the email address.

Closing.

**Comment by x-yuri** [comment]
Awesome. I can confirm that, I just obtained a certificate with `0.16.0`.
