### ISSUE TITLE
dns-01 is this an error?

### ISSUE THREAD

**Issue by dezza** [zenhack/simp_le#151]
Hello. I am trying to create a wildcard certificate with

`--email "email@example.com" -f account_reg.json -f account_key.json -f fullchain.pem -f key.pem -d '*.example.com:/simp_le/www' `

I have tried to copy `<token>` into TXT records on DNS with `_acme-challenge` `_acme-challenge.example.com` or `_acme-challenge.www.example.com` as name. However even after waiting upwards of 30mins it still does not work.

I am unsure whether this is an error or the client has halted mid-challenge.

```
2021-11-03 22:39:31,908:DEBUG:urllib3.connectionpool:437: https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/xxx HTTP/1.1" 200 380
2021-11-03 22:39:31,909:DEBUG:acme.client:1122: Received response:
HTTP 200
Server: nginx
Date: Wed, 03 Nov 2021 22:39:31 GMT
Content-Type: application/json
Content-Length: 380
Connection: keep-alive
Boulder-Requester: 266528050
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: xxx
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "recv.ws"
  },
  "status": "pending",
  "expires": "2021-11-10T17:32:09Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/xxx/xxx",
      "token": "<token>"
    }
  ],
  "wildcard": true
}
2021-11-03 22:39:31,909:DEBUG:acme.client:1147: Storing nonce: xxx
CA did not offer http-01-only challenge combo. This client is unable to solve any other challenges.
```

**Comment by zenhack** [comment]
If you want a wildcard cert you're going to need to use a different acme client; that requires using the DNS-01 challenge type, which `simp_le` does not support, and in all likelyhood never will.
