### ISSUE TITLE
New account key is not preserved on failure

### ISSUE THREAD

**Issue by zenhack** [zenhack/simp_le#16]
<a href="https://github.com/Lekensteyn"><img src="https://avatars.githubusercontent.com/u/164530?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Lekensteyn](https://github.com/Lekensteyn)**
_Tuesday Jan 05, 2016 at 20:55 GMT_
_Originally opened as https://github.com/kuba/simp_le/issues/58_

----

When an account key is created, but the authorization failed (because the HTTP server is not reachable for example), the account key key is not stored. It should probably persist this key even if it failed to generate a certificate.

Edit: what about allowing `simp_le` to generate just the account key and nothing else? I.e. allow `simp_le.py -f account_key.json` to generate the account key. Then a wrapper script can ensure that this file is available and store it appropriately.

**Comment by buchdag** [comment]
> Edit: what about allowing simp_le to generate just the account key and nothing else? I.e. allow simp_le.py -f account_key.json to generate the account key.

Got that working on a local branch.

Storing the account key on authorization failure does not seem too hard either.

**Comment by buchdag** [comment]
Okay, I've got both working.

Storing the account key on authorization failure is a no brainer, but I'm not really sure about the usefulness of being able to generate just the account key.

**Comment by zenhack** [comment]
#73 is merged, so I'm going to close.

**Comment by buchdag** [comment]
@zenhack thanks !

By the way, what is your take on enabling the separate generation of an account_key with simp_le? Useful, feature creep ?

**Comment by zenhack** [comment]
It strikes me as feature creep.
