### ISSUE TITLE
Retain order of domains

### ISSUE THREAD

**Issue by zenhack** [zenhack/simp_le#30]
<a href="https://github.com/zx2c4"><img src="https://avatars.githubusercontent.com/u/10643?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zx2c4](https://github.com/zx2c4)**
_Sunday Feb 28, 2016 at 02:19 GMT_
_Originally opened as https://github.com/kuba/simp_le/pull/80_

----

This ensures that the first domain specified on the command line will be the domain that winds up in the CN field. Otherwise, users have no way of controlling this.

This also supports Python 2.6, which is an improvement over the prior pull request. It also correctly tames pylint for an extremely widespread conditional import pattern.

It should pass all tests on Travis.

Fixes: kuba/simp_le#72
Signed-off-by: Jason A. Donenfeld Jason@zx2c4.com

----

_**[zx2c4](https://github.com/zx2c4)** included the following code: https://github.com/kuba/simp_le/pull/80/commits_

**Comment by zenhack** [comment]
<a href="https://github.com/kuba"><img src="https://avatars.githubusercontent.com/u/106176?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kuba](https://github.com/kuba)**
_Sunday Feb 28, 2016 at 15:59 GMT_

----

This is missing any kind of tests.

**Comment by zenhack** [comment]
<a href="https://github.com/zx2c4"><img src="https://avatars.githubusercontent.com/u/10643?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zx2c4](https://github.com/zx2c4)**
_Sunday Feb 28, 2016 at 16:57 GMT_

----

Okay, now it locally disables for the linter. Good thinking.

I just took a look at how you're implementing the test suite. I can struggle and grunt to add the tests to the test suite here, and in the end I'm sure it won't fit your criteria for inclusion. Would you rather we do some iterations of me struggling, or could you just add this in five minutes yourself?

**Comment by zenhack** [comment]
<a href="https://github.com/kuba"><img src="https://avatars.githubusercontent.com/u/106176?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kuba](https://github.com/kuba)**
_Sunday Feb 28, 2016 at 17:21 GMT_

----

I could try to write tests, but not in foreseeable future - unfortunately I'm extremely busy atm. If you're fine with waiting a couple of weeks before this get merged, then OK...

**Comment by buchdag** [comment]
@cpu > If I understand correctly, boulder currently derive the Subject CN from the SAN if no CN was provided in the Certificate Signing Request. How does that work exactly ? Does boulder just pick the first domain in the SAN and populate the CN with it ?

**Comment by cpu** [comment]
> If I understand correctly, boulder currently derive the Subject CN from the SAN if no CN was provided in the Certificate Signing Request.

@buchdag That's correct. We currently promote a SAN to the CN if there isn't a CN specified in the CSR.

>  How does that work exactly ? Does boulder just pick the first domain in the SAN and populate the CN with it ?

That's correct. Boulder [picks the first SAN entry and makes it the CN as well](https://github.com/letsencrypt/boulder/blob/387209dfb5bc5a907c17d8d158760811b1d32e71/csr/csr.go#L97:L100). Presently that's controlled by a flag that is always set to `true` in staging/production. In the future after a baseline requirements update we'll likely support issuing certificates without a CN and only SANs and this flag will change.

Hope that helps!

**Comment by buchdag** [comment]
That helps a ton. The ongoing work at boulder / certbot / LE is really invaluable. As is your info on boulder/le inner working.

If I'm still correct, as per RCF5280, having a (the) FQDN as Subject CN has been deprecated for ... well a while, and Boulder is going to deprecate it too in the near future, right ?

**Comment by cpu** [comment]
> If I'm still correct, as per RCF5280, having a (the) FQDN as Subject CN has been deprecated for ... well a while, and Boulder is going to deprecate it too in the near future, right ?

@buchdag Yup, exactly! That's why there's the flag to control the behaviour. I believe allowing issuance of certs with only SANs and no subject CN is blocked on a baseline requirements ballot. I can't recall offhand what the problem was but remember that we're waiting on a CA/Browser forum update to go ahead.

**Comment by buchdag** [comment]
Okay, so in my opinion there isn't anything to fix here.

**Comment by zenhack** [comment]
Works for me, closing.
