### ISSUE TITLE
Use .test. instead of .wtf. (fixes #71)

### ISSUE THREAD

**Issue by zenhack** [zenhack/simp_le#31]
<a href="https://github.com/kuba"><img src="https://avatars.githubusercontent.com/u/106176?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kuba](https://github.com/kuba)**
_Sunday Apr 17, 2016 at 19:31 GMT_
_Originally opened as https://github.com/kuba/simp_le/pull/103_

----

----

_**[kuba](https://github.com/kuba)** included the following code: https://github.com/kuba/simp_le/pull/103/commits_

**Comment by buchdag** [comment]
@cpu > correct if I'm wrong, but boulder won't work with reserved domains like .test, .example or .local right ?

**Comment by buchdag** [comment]
thanks !

@zenhack > do you have any preference regarding this ? Close the issue and keep *.wtf, replace it with *.example.com/org, replace it with another TLD in icann list ?

**Comment by zenhack** [comment]
Looks ike @kuba tried that after the .test approach failed. At a glance, the travis build log suggests that `*.example.{com,org,etc}` are also rejected:

https://travis-ci.org/kuba/simp_le/jobs/123755661

@cpu, can you confirm?

I don't really think this is super important; something like example.org would be cleaner, but if there's not a straight-forward way to do that I'm inclined to just close and forget about it.

**Comment by buchdag** [comment]
Same here, I can live with .wtf if there no both clean and easy alternative.

**Comment by cpu** [comment]
> Looks ike @kuba tried that after the .test approach failed. At a glance, the travis build log suggests that *.example.{com,org,etc} are also rejected:
>https://travis-ci.org/kuba/simp_le/jobs/123755661
>@cpu, can you confirm?

Ahh, yes. the [example hostname policy](https://github.com/letsencrypt/boulder/blob/9e763c25fbc03e60c619df86360db4bae6d6038d/test/hostname-policy.json) that Boulder includes in master blacklists those hostnames. You can either replace this file before starting Boulder or work around it with a different example name.

**Comment by zenhack** [comment]
Okay, that's what I suspected. I'm just going to close this and live with the current situation.
