### ISSUE TITLE
Update to acme 0.11.x

### ISSUE THREAD

**Issue by pradeepchhetri** [zenhack/simp_le#48]
Hi 

I was trying to upgrade `certbot` in nixos (https://github.com/NixOS/nixpkgs/pull/22239) I realized that because of https://github.com/zenhack/simp_le/blob/0.1.1/setup.py#L11 it is breaking `simp_le` package over there. 

Thanks.

**Comment by zenhack** [comment]
The reason is just that afaik acme Python doesn't make any API stability guarantees, so it isn't necessarily safe to assume newer versions of the library will

**Comment by zenhack** [comment]
...be compatible. (This is what I get for trying to type on a phone...)

I'm happy to raise the cap if a newer version has been tested. I'll try out a new version soonish and push the change to master if it passes CI.

Thanks for pointing this out.

**Comment by pradeepchhetri** [comment]
Thank you for the quick reply. I will try out `simp_le` with `acme-0.11.1` (latest version) and will open a pull request if everything works fine.

**Comment by zenhack** [comment]
@pradeepchhetri, any luck?

**Comment by zenhack** [comment]
I tried this myself; travis failed. The test runs are choking on something to do with the docker images for boulder, which I need to investigate. The linter run though noticed that a method we're calling grew a new argument (rsn) in the new version:

https://letsencrypt.readthedocs.io/projects/acme/en/latest/api/client.html#acme.client.Client.revoke

So there actually is a compatibility issue with the new version.

It would be good to be able to use the more recent version; I don't want simp_le to fall too far behind. This might be as simple as passing in 0 (which seems to mean "unspecified"), but I want to sit down and understand this properly before moving forward.

I'm going to change the title of this issue and use it to track updating to the newest version.

**Comment by cpu** [comment]
> I tried this myself; travis failed. The test runs are choking on something to do with the docker images for boulder, which I need to investigate
I filed #49 for this

**Comment by zenhack** [comment]
Finally got around to this; We're using 0.11.x on master now. Closing.
