### ISSUE TITLE
Update travis.sh to not rely on boulder-tools "latest" tag

### ISSUE THREAD

**Issue by cpu** [zenhack/simp_le#49]
Hi there,

Happened to see this comment from @zenhack on https://github.com/zenhack/simp_le/issues/48:
> I tried this myself; travis failed. The test runs are choking on something to do with the docker images for boulder, which I need to investigate.

We deleted the `latest` tag for the boulder-tools docker image (https://github.com/letsencrypt/boulder/issues/2030) because the semantics of that label in dockerhub didn't match the way we were using it. Your builds are failing as a result (we [fixed the same thing](https://github.com/letsencrypt/boulder/pull/2569) in our own CI incidentally).

I believe you can just [delete the explicit docker-pull for the boulder-tools image](https://github.com/zenhack/simp_le/blob/777585fb73c4ba7a0c6a62e81db7c14b71305e88/tests/travis.sh#L21) from your setup script to fix. The `docker-compose pull`  [above](https://github.com/zenhack/simp_le/blob/777585fb73c4ba7a0c6a62e81db7c14b71305e88/tests/travis.sh#L20) is pulling in the correct boulder-tools tag already.

**Comment by cpu** [comment]
I also apologize for breaking your builds :-) I didn't realize there were down-stream implications at the time we deleted the tag. :wilted_flower:

**Comment by zenhack** [comment]
Thanks for the tip; I've pushed your suggested fix to a branch and will merge into master if travis passes.

**Comment by zenhack** [comment]
Seems to fix the docker issue, but there's some other failures, probably unrelated:

https://travis-ci.org/zenhack/simp_le/builds/205102518

I need to make sure travis gets run more often -- development isn't active enough to catch this kind of bitrot in a timely manner otherwise.

**Comment by cpu** [comment]
@zenhack Glad to hear it fixed your Boulder problem. Unfortunately I won't be much help with the unrelated failures :-) I'll let you close the issue once you're set. Thanks!

**Comment by zenhack** [comment]
Finally got around to looking at the other build failures; they seem to have been transient issues with networks/other people's infrastructure. I re-ran them and they passed, so I've merged the fix to master.

@cpu, thanks again for your help.

**Comment by zenhack** [comment]
*sigh* reopening. We're stilling getting intermittent failures, on different parts of the matrix each time:

https://travis-ci.org/zenhack/simp_le/jobs/207791710#L771

Looks like it's a problem with setting up rabbitmq, which is all done by the boulder docker container. @cpu, any insight on that one? Since it's intermittent, I wonder if there's just a timeout that's too short or something.

**Comment by cpu** [comment]
> Looks like it's a problem with setting up rabbitmq, which is all done by the boulder docker container. @cpu, any insight on that one? Since it's intermittent, I wonder if there's just a timeout that's too short or something.

@zenhack Interesting - that's possible, but I haven't seen this particular timeout in our own CI. You could try increasing the `rpcTimeout` value in `test/config/ra.json` from `"15s"` to something larger to see if that's all that is required here.

Alternatively, since this is RabbitMQ related you could try using the gRPC configuration that doesn't use Rabbit. We're [very close to switching to this](https://community.letsencrypt.org/t/changing-our-rpc-system-in-staging/28462) and completely removing Rabbit. To do that now you could try [updating the `docker-compose run`](https://github.com/zenhack/simp_le/blob/e020bd6e6b906b2e2129cf9927571bfc92af7f6b/tests/travis.sh#L22:L25) to use `-e BOULDER_CONFIG_DIR=test/config-next` instead of the default `test/config`. 

(Reminder if you want to try both strategies at once to update the `test/config-next/ra.json` timeout as well as `test/config/ra.json`)

I'd be interested to hear if either of these work. If they don't I can help dig further.

**Comment by zenhack** [comment]
@cpu, increasing the timeout (to 60s) did the trick. Using config-next gave a different error:

https://travis-ci.org/zenhack/simp_le/jobs/208482001

Which I still want to take the time to understand, but this issue is closed.

**Comment by cpu** [comment]
@zenhack Great - glad the timeout approach worked!
