### ISSUE TITLE
Validate hostname arg to -d option.

### ISSUE THREAD

**Issue by esmail** [zenhack/simp_le#51]
Is it at all possible to specify an alternative port at which the challenge file is served? Currently, the only obvious place to specify a port number is in the domain (e.g. `simp_le -d example.com:8080 ...`) which ends up with the port interpreted as the local webroot path.

The reason I ask is because I'm trying to use [JrCs/docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) (which relies on `simp_le`) and [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) to manage serving Docker containers for me, but my ISP (RCN) blocks incoming requests on port 80. In lieu `tls-sni-01` challenge mode support in `simp_le`, I'm wondering if there's something I can do short of setting up an external server to reverse proxy with HTTPS passthrough.

Related:
https://github.com/kuba/simp_le/issues/89
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/42

**Comment by zenhack** [comment]
From <https://tools.ietf.org/html/draft-ietf-acme-acme-06#page-47>:

```
   3.  Dereference the URI using an HTTP GET request.  This request MUST
       be sent to TCP port 80 on the HTTP server.
```

http-01 is the only mechanism that simp_le supports (by design), so unless there's a change in the spec this isn't going to happen -- sorry.

**Comment by zenhack** [comment]
simp_le probably *should* validate the host name and complain if you put a port in though, so I'm going to change the title of this and use it to track that issue.

**Comment by esmail** [comment]
Thanks for the speedy response! Understood. At least I've got a workable way around it with a reverse proxy server and a temporary DNS change.

**Comment by buchdag** [comment]
`simp_le probably should validate the host name and complain if you put a port in though`

How do you see this ? Should it fail if you put any port or should it silently strip the port if you put :80 or :443 and fail validation for any other port ?

**Comment by buchdag** [comment]
Self answer : as the -d / --vhost argument can take both domain and webroot path separated by a `:`, it should complain if any port is inputed at all.

If you do `simp_le -d example.com:8080`, it will currently treat `8080` as the path to the webroot (and fail).

**Comment by zenhack** [comment]
Was thinking about this again recently. Theoretically, example.com:8000 could denote a webroot named "8000", though most likely it's a mistake. Maybe the thing to do is check if the webroot is a number < 2 ** 16, and issue a warning along the lines of "this looks like a port number, but that's not what this field is."

**Comment by buchdag** [comment]
As it is; the class method responsible for the domain / webroot splitting [will only split on a `:` once](https://github.com/zenhack/simp_le/blob/master/simp_le.py#L278), so if you pass something like `example.com:8000:/path/to/root`, you'll have `8000:/path/to/root` as a path to your webroot.

Does `simp_le` work with a relative webroot path like `path/to/webroot` ?

If no we just have to check that the webroot start with a `/`.

If yes that might be a bit more complex than expected, because `8080:webroot` is a valid directory name.

**Comment by zenhack** [comment]
Quoting Nicolas Duchon (2017-08-14 13:17:01)

>    Does simp_le work with a relative webroot path like path/to/webroot ?

It does.

>    If yes that might be a bit more complex than expected, because
>    8080:webroot is a valid directory name.

Sure. I think the general strategy of warning on likely mistakes is
reasonable though. We could do something like:

```python
if re.match(r'^[0-9]{1,5}($|:)', webroot):
    logger.warn('Warning: your webroot path (%s) looks like it '
                'contains a port number; this should be a directory '
                'name. Continuing anyway, but this may not be what '
                'you intended...', webroot)
```

The goal is just to help with diagnostics; that regex should be close
enough given it's just a warning.
