### ISSUE TITLE
Question: main page says the build fails - will current version work?

### ISSUE THREAD

**Issue by polapi** [zenhack/simp_le#53]

**Comment by zenhack** [comment]
It should be fine. The "build" failure is a problem with the testing
infrastructure itself; I think a bit of bitrot having to do with pylint
that I haven't gotten around to fixing. Here's the actual error:

    https://travis-ci.org/zenhack/simp_le/jobs/230599027#L548

Apparently we're passing an option to pylint that it doesn't recognize
(anymore). So I need to get around to fixing that, but it shouldn't
affect users at all.

**Comment by zenhack** [comment]
Build is passing again, going to close this.
