### ISSUE TITLE
No tag for 0.3.0

### ISSUE THREAD

**Issue by buchdag** [zenhack/simp_le#57]
The README mentions a 0.3.0 release, yet there is no corresponding tag on the repo (the most recent one is 0.2.0).

Would it be possible to add a tag for this release, or is it still considered unreleased ?

**Comment by zenhack** [comment]
Per the note at the top of the ChangeLog section, sometimes the most
recent entry is as-yet-unreleased, as is the case right now. But thanks
for the reminder; I've been meaning to tag it & upload it to PyPI. Will
get to that in the next day or so.

Quoting Nicolas Duchon (2017-06-26 11:59:36)

>    The README mentions a 0.3.0 release, yet there is no corresponding tag
>    on the repo (the most recent one is 0.2.0).
>
>    Would it be possible to add a tag for this release, or is it still
>    considered unreleased ?

**Comment by buchdag** [comment]
Works for me, thanks for the answer !

**Comment by zenhack** [comment]
Ok, this is tagged and uploaded to pypi now.

**Comment by buchdag** [comment]
Thanks ! 👍
