### ISSUE TITLE
Reuse account_key.json

### ISSUE THREAD

**Issue by mikew** [zenhack/simp_le#71]
I've been getting rate limit errors, and [the certbot / boulder devs are suggesting reusing account_key.json](https://community.letsencrypt.org/t/getting-rate-limits-but-no-obvious-reason/42478/3?u=mikew), but I'm not seeing any ability to do that in simp_le.

Is it something you're planning on adding? Or should I just copy an existing `account_key.json` into a new cert folder before running simp_le?

**Comment by zenhack** [comment]
Quoting mikew (2017-09-18 14:03:38)

> Or should I just copy an existing account_key.json into a new cert
> folder before running simp_le?

This is what I do. I'd be amenable to accepting a patch that adds a
command line flag specifying the location of the file, but I'm unlikely
to do so myself any time soon.

**Comment by buchdag** [comment]
Got that working. I'm just wondering if it does not contradict point 10 of the manifesto:

> Do not allow specifying output file paths. Users should symlink if necessary!

Because the way I did it, if the file does not exist at the provided path, it will attempt to create it there. So that's pretty much the same as specifying an output file path for `account_key.json`

**Comment by zenhack** [comment]
Quoting Nicolas Duchon (2017-10-05 06:52:09)

>    Got that working. I'm just wondering if it does not contradict point 10
>    of the manifesto:
>
>      Do not allow specifying output file paths. Users should symlink if
>      necessary!

Point. I'd rather err on the side of leaving things out so, let's leave
this as-is.

**Comment by zenhack** [comment]
Going to close this, looks like it's resolved.
