### ISSUE TITLE
release 0.6.0

### ISSUE THREAD

**Issue by buchdag** [zenhack/simp_le#80]
Could we tag and release 0.6.0 following the ACME version bump to 0.20 on november 8 ?

It's been on "upcoming" for a while.

**Comment by zenhack** [comment]
Yeah, this has been on my mind lately. I have renewing the certs on zenhack.net slated for nov 9, so I'll bump acme and do that with master, and if all goes well I'll tag 0.6.

**Comment by zenhack** [comment]
0.6 is tagged and on PyPI, closing.

acme 0.20 doesn't seem to be out yet, so I haven't bumped the version.
