### ISSUE TITLE
Docker automated build and tagged versions

### ISSUE THREAD

**Issue by buchdag** [zenhack/simp_le#84]
Looks like automated builds on Dockerhub still don't trigger on new commits to master, last one was 10 days ago.

It might not be clear from the wording but _"When active, builds will happen automatically on pushes"_ has to be checked for this to work.

Also it would be nice to have tagged version on Dockerhub starting with 0.6.0 but this require building the image locally (as by default the Dockerfile will always build from latest commit on master) and then pushing it manually to Dockerhub.

If you don't have time to handle this you can add me as a collaborator on Dockerhub (my nick there is duch), I'll be glad to help.

**Comment by zenhack** [comment]
Quoting Nicolas Duchon (2017-11-10 12:31:01)

>    Looks like automated builds on Dockerhub still don't trigger on new
>    commits to master, last one was 10 days ago.

Darn.

>    It might not be clear from the wording but "When active, builds will
>    happen automatically on pushes" has to be checked for this to work.

Yeah, that box is checked.

>    If you don't have time to handle this you can add me as a collaborator
>    on Dockerhub (my nick there is duch), I'll be glad to help.

Done; thanks.

**Comment by buchdag** [comment]
Okay administrative rights over the registry settings seems to be reserved to organisations and teams, I guess we'll see later why Automated Build don't trigger.

At least I can manually push to the registry now, just done that for `0.6.0` and `latest` tags, I'll try to keep `latest` in sync with new commits. It's not like there are tens of commits a day anyway.

**Comment by zenhack** [comment]
Ok, cool.
