### ISSUE TITLE
Outdated ToS Hash default - new-registration errors from URL change

### ISSUE THREAD

**Issue by cpu** [zenhack/simp_le#85]
Hi there,

It looks like `simp_le` ~hardcodes (the hash, not the URL) the Let's Encrypt ToS in its defaults: 

https://github.com/zenhack/simp_le/blob/067e713bca8a8825a2e5bf5036ca4526818e2115/simp_le.py#L991:L995

The ToS URL [**changed November 15th**](https://community.letsencrypt.org/t/subscriber-agreement-update-november-15-2017/45607). New registration requests using this ACME client and the default hash value will produce an error as of today. 

This is breaking upstream projects: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/277

I did a pass on other open source ACME clients trying to catch this ahead of time but was searching Github by the ToS URL not the hash and missed this one, sorry folks.

Is there any way to avoid hardcoding this hash? The ACME protocol supports providing the current ToS URL to the client at runtime in two ways: via the /directory `meta` key and as part of the new-reg flow when the initial account object doesn't contain an agreement field. It would be great if `simp_le` could match other clients that do not require code changes when the ToS URL changes.

Thanks!

**Comment by buchdag** [comment]
Hi @cpu 

For a urgent fix PR, the new ToS hash appears `cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b`, can you confirm ?

**Comment by cpu** [comment]
@buchdag That's correct. :+1:

**Comment by zenhack** [comment]
I've merged #86 and released it. #87 will be a better long-term solution, but I'm going to close this for now.
