### ISSUE TITLE
Keep challenge files in case of authorization error

### ISSUE THREAD

**Issue by buchdag** [zenhack/simp_le#92]
@zenhack I thought it might be useful for troubleshooting purpose to do a simple adjustment on 212acd3efa6090641845bc08b63a512b082e0cb0 and have `simp_le` remove challenge files only on successful domain authorization rather than wether the authorization succeed or not. Do you agree ?

**Comment by zenhack** [comment]
Have you found yourself wanting this when debugging?

It sounds like a plausible use case, but I've never found myself digging through the challenge files, so I want to make sure we're not adding functionality that no one is actually going to use.

**Comment by buchdag** [comment]
Not while using `simp_le` in standalone, but with `letsencrypt-nginx-proxy-companion` it's quite common to curl the challenge file in order to troubleshoot a failed domain validation.

[This comment in particular](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/209#issuecomment-347359735) made me think that people are probably going to look after the challenge file only when a validation fails and might draw wrong conclusions from the fact that the file has been deleted.

**Comment by buchdag** [comment]
I recognize that the file itself and its content are completely irrelevant to the troubleshooting process, you might as well `echo 'Hello, world' > hello-world` on the webroot and try to curl this file instead.

**Comment by zenhack** [comment]
Ok, just wanted to sanity check that it's really useful; I'm convinced of that now.

My other concern is about generating garbage in the challange directory. It would be nice to avoid littering the directory with failed attempts.

**Comment by buchdag** [comment]
Agreed, just keeping every challenge file that the validation server fails to get kind of undo https://github.com/zenhack/simp_le/commit/212acd3efa6090641845bc08b63a512b082e0cb0.

Do you think this (the challenge file mentioned in the error message being  automatically deleted) might be an issue for the standalone `simp_le` too or is it more specific to project that use it like `letsencrypt-nginx-proxy-companion` ?

**Comment by zenhack** [comment]
Quoting Nicolas Duchon (2017-12-03 15:19:14)

>    Do you think this (the challenge file mentioned in the error message
>    being automatically deleted) might be an issue for the standalone
>    simp_le too or is it more specific to project that use it like
>    letsencrypt-nginx-proxy-companion ?

Like I said, I've never really found myself wanting this. Though, I've
not had simp_le fail very often either.

My inclination is to leave things as they are unless it becomes clear
that it's a real problem. Maybe we could just log the fact that we're
deleting those files at info level instead of debug?

**Comment by buchdag** [comment]
> Maybe we could just log the fact that we're deleting those files at info level instead of debug?

I'd say that would be enough.
