### ISSUE TITLE
Clear release schedule

### ISSUE THREAD

**Issue by zenhack** [zenhack/simp_le#94]
There have been several occasions where folks have pinged me with some variant of "when are you going to do a relase?"

We should come up with a clear policy, document it, and follow it.

What I've kindof been doing is dogfooding master to update zenhack.net, and if all goes well tag a relase, plus maybe do something in between if folks bug me or it's a bit more pressing. This would basically amount to an every-2-months time based schedule. Open to other suggestions.

**Comment by zenhack** [comment]
@buchdag, thoughts?

**Comment by buchdag** [comment]
Yep, LGTM.

**Comment by zenhack** [comment]
Quoting Nicolas Duchon (2017-12-11 11:54:57)

> The only caveat I can think of is ACME that appears to be targeting
> monthly releases since 0.10, so we'll probably bump the ACME version
> two times between each simp_le release. Is this an issue ?

My intuition is that dogfooding it first is worth the trade-off. We can
pay attention and see if anyone is regularly having a problem because of
this and change if need be.

OK, I'm going to document this as official practice then.
