### ISSUE TITLE
Should we remove the Terms of Service hash stuff ?

### ISSUE THREAD

**Issue by buchdag** [zenhack/simp_le#95]
As I was beginning to suspect, it turns out that the whole ordeal with Terms of Service hash is actually not required. I just ran the integration test against [a version that had all the ToS hash bits removed](https://github.com/buchdag/simp_le/commit/10ebe59e80c9de2df23ca76ee1b52f37119e38fb) and just do `client.agree_to_tos()` when `client.directory.meta.terms_of_service` is not `None`.

Works just fine (tried against the LE staging endpoint too).

So what I did with #88 actually make `simp_le` compare two hashes of the same file at the same URI, the only difference being how it got that URI. That's pretty pointless to say the least, we could as well replace that with `if 2 is 1 + 1:`.

I guess the original idea behind the hash thing was to compare the hash of the latest ToS with the hardcoded version and fail if they differ, telling you that the ToS were updated and that you should probably go read them again before updating the hardcoded hash. But that wasn't documented anywhere so we just assumed that the intention was to automatically agree to the ToS.

@cpu Am I missing something, like a legal obligation for ACME clients to have that kind of mechanism, even if it acts the same as "agree automatically" ? 

If not I think we should rather go for automatic agreement to the ToS if present, remove the hash related code and warn both in the client and in the doc that using simp_le implies agreeing to the terms of service of the ACME CA, with a link to LE's policy and legal repository.

**Comment by cpu** [comment]
> @cpu Am I missing something, like a legal obligation for ACME clients to have that kind of mechanism, even if it acts the same as "agree automatically" ?
>
> If not I think we should rather go for automatic agreement to the ToS if present, remove the hash related code and warn both in the client and in the doc that using simp_le implies agreeing to the terms of service of the ACME CA, with a link to LE's policy and legal repository.

IANAL but that sounds ~reasonable to me. The ACME v2 account creation flow just has the client send "terms-of-service-agreed: true" and doesn't bother with getting the URL sent back. Basically as long as your users understand they are bound by the subscriber agreement if they choose to use Let's Encrypt I think you're good :+1:

**Comment by zenhack** [comment]
Works for me.
