### ISSUE TITLE
Too much logs to STDERR

### ISSUE THREAD

**Issue by paulusd** [zenhack/simp_le#97]
Hi,
following log ist written to STDERR.
`2017-12-26 03:53:43,170:INFO:simp_le:1534: Certificates already exist and renewal is not necessary, exiting with status code 1.`

Is it possible to write logs like this to STDOUT?

Background:
I use the [docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion)
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/310

**Comment by zenhack** [comment]
It's not obvious to me why it should be stdout, rather than stderr?

**Comment by paulusd** [comment]
I use Graylog as log managment tool and there I can split the messages from stdout and stderr.
Stderr logs usually indicate an error that requires me to respond.
Although I can rewrite the logs with graylog, but it would be nice if simp_le only writes error messages to stderr.

**Comment by zenhack** [comment]
I'm disinclined to add anything particularly complex here; splitting the
stream based on log level seems like something that really belongs in
the log management tool. But I'd be willing to accept patches for either
or both of:

* A `--log-level` option, that would let you set log level to any level,
  so e.g. you could restrict the output to warn and higher. That sounds
  like it would be enough for the use case you've described.  We already
  have a `-v/--verbose` flag that lets you increase the amount of
  logging, but not decrease it.
* An option to output logs in a more machine-readable format (e.g.
  JSON). This would make scripting around the logging easier in general.

Would either of those be sufficient for you?

**Comment by paulusd** [comment]
Thank you for your answer.
The first option would help me, but sorting the logs in the log managment tool is the better option
